[[redirects]]
  from = "/api/*"
  to = "https://myvoice-be.vercel.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ads.txt"
  to = "/ads.txt"
  status = 200

[[redirects]]
  from = "/app-ads.txt"
  to = "/app-ads.txt"
  status = 200

[[redirects]]
  from = "/privacy-policy.html"
  to = "/privacy-policy.html"
  status = 200

[[redirects]]
  from = "/privacy-policy"
  to = "/privacy-policy.html"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200